name: Publish resume in JSONResume format

on:
  push:
    branches: [ main, test ]
    paths:
      - 'resume.json'

  # Run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_run:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - uses: actions/checkout@v3
      - uses: kelvintaywl/action-jsonresume-export@v1
        name: Export resume as HTML
        with:
          theme: class-yaucp
          resume_filepath: resume.json
          output_filepath: dist/index.html
      - name: Commit published HTML
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain dist/index.html)" ]; then
            git add dist/index.html
            git commit -m "chore(dist/index.html): Update Resume Page"
            echo name=exit_code::0 >> $GITHUB_OUTPUT
          else
            echo name=exit_code::1 >> $GITHUB_OUTPUT
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.commit.outputs.exit_code == 0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
